- name: Create Jenkins Jobs
  hosts: localhost
  connection: local
  vars:
    jobs:
      - roboshop-terraform
      - cart
      - catalogue
      - user
      - shipping
      - payment
  roles:
    - jenkins-jobs